---
### [Change System Name] kunotest
AWSTemplateFormatVersion: "2010-09-09"
Description: Create ECR Repository

Parameters:
  SystemName:
    Description: System Name
    Type: String
    Default: kunotest ### [Change System Name]
  Environment:
    Description: Environment
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - stg
      - dev

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
          - SystemName
          - Environment

Resources:
  ## ECR: Repository (App)
  ECRRepositoryApp:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${SystemName}-${Environment}-app
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire images count more than 3",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 3
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

  ## ECR: Repository (Web)
  ECRRepositoryWeb:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub ${SystemName}-${Environment}-web
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Expire images count more than 3",
                "selection": {
                  "tagStatus": "any",
                  "countType": "imageCountMoreThan",
                  "countNumber": 3
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }

Outputs:
  ## ECR: Repository (App)
  ECRRepositoryApp:
    Value: !Ref ECRRepositoryApp
    Export:
      Name: !Sub ${AWS::StackName}-ECRRepositoryApp

  ECRRepositoryAppArn:
    Value: !GetAtt ECRRepositoryApp.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ECRRepositoryAppArn

  ## ECR: Repository (Web)
  ECRRepositoryWeb:
    Value: !Ref ECRRepositoryWeb
    Export:
      Name: !Sub ${AWS::StackName}-ECRRepositoryWeb

  ECRRepositoryWebArn:
    Value: !GetAtt ECRRepositoryWeb.Arn
    Export:
      Name: !Sub ${AWS::StackName}-ECRRepositoryWebArn
